### ISSUE TITLE
请问airdrop能用吗？

### ISSUE THREAD

**Issue by P8CM** [xuelingkang/hackintosh-opencore-mag-b460m-mortar-wifi-10700-uhd630-igpu#1]
请问用板载Wi-Fi、蓝牙 airdrop 能用吗？

**Comment by xuelingkang** [comment]
![image](https://user-images.githubusercontent.com/42362195/110239847-2bab7680-7f84-11eb-864b-972558f8ac2f.png)
我在隔空投送中能看到手机，但是发送文件总是收不到，不知道是不是我的操作问题

**Comment by xuelingkang** [comment]
蓝牙没问题，板载wifi有时候会断，我一直用的网线
