### ISSUE TITLE
UTBMap.kext需要与USBToolBox.kext配合使用

### ISSUE THREAD

**Issue by klniu** [xuelingkang/hackintosh-opencore-mag-b460m-mortar-wifi-10700-uhd630-igpu#10]
如题，这个是不是USB不好用的原因？

**Comment by xuelingkang** [comment]
UTBMap和USBToolBox是另一种比较简单的USB映射方式吧，我好像从别的EFI里面搬运过，也没有解决问题。
我是按照OpenCore官方文档做的USBMap，这个不需要USBToolBox。
我现在的系统版本是12.3.1，已经超过11.3了，所以不管是哪种方式，我这边都不能尝试了。
如果你那有做好的，希望能分享一下。

**Comment by klniu** [comment]
哦，不懂那么多， 我是看到UTBMap才发来提问的，我们的机型不一样，我这个机型我刚开始准备做，看看会不会出现您说的问题，我的是天逸510Pro-141imb的。过几天反馈。

**Comment by xuelingkang** [comment]
好的，如果要自己映射USB可以先装11.3以下的版本，没问题了再升上去。

**Comment by klniu** [comment]
好的，我试试，多谢
