### ISSUE TITLE
节能和USB3.0的问题

### ISSUE THREAD

**Issue by wjllp** [xuelingkang/hackintosh-opencore-mag-b460m-mortar-wifi-10700-uhd630-igpu#11]
系统版本：MacOS 12.6
配置：除了没独显，其他的跟你一样
1、同一套EFI，用u盘引导的时候，节能有5项，用硬盘引导的时候节能只有4项，少了个“使硬盘休眠”，我自己配置的EFI和你这套EFI都有这个问题。
2、USB3.0接口能识别U盘，但是U盘插上去只有2.0的速度，好像很多人都有这个问题，目前还没看到有啥好的解决办法。

除了这两个问题不完美，其他的都非常完美了，XHCI-unsupported.kext这个好像没啥用，我删了它没发现任何影响

**Comment by xuelingkang** [comment]
我这边用硬盘引导也是5项，按说用什么引导应该都一样的。
XHCI-unsupported.kext，我不加这个USB3.0的接口就不能识别3.0的U盘。
3.0的速度问题也可以接受，不是经常拷文件。如果有需要的话，可以用typec接口的移动硬盘，从移动硬盘拷文件能到100多M每秒，typec口在机箱后面，不太好插
