### ISSUE TITLE
关于Ventura 13.2.1无法驱动wifi的问题

### ISSUE THREAD

**Issue by doudouyoutang17** [xuelingkang/hackintosh-opencore-mag-b460m-mortar-wifi-10700-uhd630-igpu#12]
在0.8.9下存在wifi无法驱动的问题，尝试更新驱动无果。

**Comment by xuelingkang** [comment]
参考一下这个[WiFi and Bluetooth](https://dortania.github.io/OpenCore-Install-Guide/ktext.html#intel)

Ventura版本没有正式发布的AirportItlwm，所以需要使用Itlwm代替，配套使用Heliport连接wifi。
![image](https://user-images.githubusercontent.com/42362195/225220605-5cfd9386-0458-4b61-978e-bcf4cb044c22.png)

**Comment by doudouyoutang17** [comment]
已解决问题,谢谢
