### ISSUE TITLE
大佬现在在用哪个版本的呢？

### ISSUE THREAD

**Issue by CANBAAA** [xuelingkang/hackintosh-opencore-mag-b460m-mortar-wifi-10700-uhd630-igpu#13]
两年前用您的efi安装了Catalina，稳定使用了两年，现在买了块大点的SSD，想装新点的版本，大佬有推荐嘛？

**Comment by xuelingkang** [comment]
不用客气，我现在用的12，我也是经常在11、12、13这几个版本来回折腾，最近不想折腾了，12用了挺久。
11开始风格变化挺大的，后面每个版本都有一些新特性，可以比较一下。
如果想用13的话，我这个仓库的efi不支持wifi，最新的[AirportItlwm](https://github.com/OpenIntelWireless/itlwm/releases)已经支持13了，如果有兴趣可以试试
