### ISSUE TITLE
蓝牙可以打开但是无法搜索到设备

### ISSUE THREAD

**Issue by tinycolds** [xuelingkang/hackintosh-opencore-mag-b460m-mortar-wifi-10700-uhd630-igpu#15]
大佬，我安装的后替换 EFI，其它都正常，就是蓝牙无法搜索到设备，请问下你又遇到这个情况嘛
* 系统 `12.6.8`
* 其它硬件一致

**Comment by xuelingkang** [comment]
我还没有遇到过呢。
建议使用其他蓝牙设备也尝试一下，或者重新打开设备的配对模式，使设备处于可以被发现的状态。

**Comment by tinycolds** [comment]
好的好的，感谢回复，我再试试
