### ISSUE TITLE
板载WIFI 蓝牙

### ISSUE THREAD

**Issue by Conor-Jin** [xuelingkang/hackintosh-opencore-mag-b460m-mortar-wifi-10700-uhd630-igpu#2]
老哥我想了解下，这款主板的板载WIFI、蓝牙的情况

看上个ISSUES，是不可以理解，这个板载WIFI正常使用，蓝牙的airdrop 可能用不了，蓝牙链接耳机可以么，板载有线也是正常使用对吧？

是这样我是非苹果生态用户，如果迫击炮的WIFI版本可以使用 WIFI、蓝牙，我就不配置苹果免驱网卡了

**Comment by xuelingkang** [comment]
我偶尔会发现wifi断了，自动重连，蓝牙耳机没问题，有线网络也没问题
