### ISSUE TITLE
使用浏览器浏览页面的时候滑动掉帧

### ISSUE THREAD

**Issue by CANBAAA** [xuelingkang/hackintosh-opencore-mag-b460m-mortar-wifi-10700-uhd630-igpu#4]
Safari和edge都会有这个问题，有点难受，和你是一样的配置，10700加460MWIFI，用的也是核显UHD630，你这边会有这个问题吗？

**Comment by xuelingkang** [comment]
没用过这两个浏览器，Chrome有这种现象吗，会不会是屏幕的问题

**Comment by CANBAAA** [comment]
> 没用过这两个浏览器，Chrome有这种现象吗，会不会是屏幕的问题
下载了个mos，解决了，因为没有触摸板，直接用鼠标滚轮滑动的，所以有这个问题，还以为是系统问题
