### ISSUE TITLE
USB3.0修复好了嘛

### ISSUE THREAD

**Issue by evan-xie** [xuelingkang/hackintosh-opencore-mag-b460m-mortar-wifi-10700-uhd630-igpu#5]

**Comment by xuelingkang** [comment]
这个说来话长了，应该不是版本或者映射的问题
因为我把操作系统和OpenCore都降级到之前的版本也不能恢复正常
后来我抹掉系统重装了一遍，usb3偶尔能用，但是我把软件配置等搞好之后，发现又不能用了
主板烧坏返厂过一次，我感觉也有可能是我的硬件问题
现在看开了，就这样凑合着吧
