### ISSUE TITLE
大佬，请教下要安装Catalina的话，需要改哪些配置呢？

### ISSUE THREAD

**Issue by CANBAAA** [xuelingkang/hackintosh-opencore-mag-b460m-mortar-wifi-10700-uhd630-igpu#6]

**Comment by CANBAAA** [comment]
已经安装完成，还有一个问题就是，在登陆页面显示是已经连上了Wi-Fi，但是输入密码进入系统后，他又重新连接Wi-Fi了。。。

**Comment by CANBAAA** [comment]
![IMG_0965](https://user-images.githubusercontent.com/39176450/124698652-dd02ee80-df1b-11eb-8d4f-0af17b79fa2c.JPG)
![IMG_0966](https://user-images.githubusercontent.com/39176450/124698656-df654880-df1b-11eb-86e3-bd612bd35623.JPG)

**Comment by xuelingkang** [comment]
这套驱动可以装catalina，需要换一下无线网驱动
[AirportItlwm](https://github.com/OpenIntelWireless/itlwm/releases)
![image](https://user-images.githubusercontent.com/42362195/124706027-36bde580-df29-11eb-9687-11c6a74202f3.png)
至于WIFI的连接状态显示问题，我没有注意过，使用没问题就可以了吧。
