### ISSUE TITLE
唤醒 及 USB 失效的建议

### ISSUE THREAD

**Issue by BI4LDK** [xuelingkang/hackintosh-opencore-mag-b460m-mortar-wifi-10700-uhd630-igpu#7]
一直连着的USB设备 需要内建，否则睡眠不了 表现就是一睡就醒 
XhciPortLimit在Big Sur11.3及以上版本失效，会造成部分USB接口失效，暂时只能通过定制USB解决。

**Comment by BI4LDK** [comment]
config.plist配置文件，找到选项Kernel——Quirks——XhciPortLimit，取消勾选XhciPortLimit

**Comment by xuelingkang** [comment]
多谢，XhciPortLimit我没有打开，周末我试试把一直连接的USB类型改成内建。
