### ISSUE TITLE
可以考虑删除framebuffer-stolenmem

### ISSUE THREAD

**Issue by kksxsyj** [xuelingkang/hackintosh-opencore-mag-b460m-mortar-wifi-10700-uhd630-igpu#9]
外接4k显示器的时候不能自动开启hidpi还只能使用2k分辨率，删除DeviceProperties —> framebuffer-stolenmem后就正常了

**Comment by xuelingkang** [comment]
多谢，我试试，既然DP能正常输出，应该就是转HDMI出了问题，我也考虑换个DP显示器
